import './globals.css'
import { TaskProvider } from '../context/TaskContext'

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app'
}

export default function RootLayout ({ children }) {
  return (
    <html lang='en'>
      <body>
        <h1>Navigation</h1>
        <TaskProvider>
          {children}
        </TaskProvider>
      </body>
    </html>
  )
}
